### ISSUE TITLE
WorldBossTimers/KillInfo.lua:190: attempt to index field 'db' (a nil value)

### ISSUE THREAD

**Issue by Fiamma29** [fstenstrom/world-boss-timers#117]
Immediately upon login this error pops at an approximate rate of 10 per second. Just... brrrr number goes up. Every time the count goes up the text deselects which made copying this one a little tricky, but I managed it! It doesn't stop until reload, at which point it starts again. Text never changes.

Please let me know if I can provide any additional info, thank you!

234x WorldBossTimers/KillInfo.lua:190: attempt to index field 'db' (a nil value)
[string "@WorldBossTimers/KillInfo.lua"]:190: in function `GetLatestRespawnTimePoint'
[string "@WorldBossTimers/KillInfo.lua"]:243: in function `ShouldRespawnAlertPlayNow'
[string "@WorldBossTimers/WorldBossTimers.lua"]:800: in function <WorldBossTimers/WorldBossTimers.lua:795>

Locals:
self = <table> {
 map_id = 2200
 announce_times = <table> {
 }
 boss_name = "Balboan"
 realm_name_normalized = "Saurfang"
 version = "v1.12"
 realm_name = "Saurfang"
 has_triggered_respawn = false
 t_death = 1701905303
 shard_id = 10113
}
(*temporary) = 1701905303
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"

**Comment by fstenstrom** [comment]
Thanks for reporting. I haven't yet added any DF rares, and since `boss_name = "Balboan"` my guess is that your `BossData.lua` was patched to contain some extra rares. Then the addon was updated, and the patched `BossData.lua` was overwritten with the original, so when trying to load the timer for Balboan, it fails because that rare no longer exists in that file.

Or maybe the timer was shared by someone with a patched file, but I think there's a check preventing that.

Does this sound reasonable?

**Comment by Fiamma29** [comment]
It does, absolutely. Thanks for the in depth reply!

I added Houndlord Ren as a custom rare back in March 2023, and I believe I also grabbed a patched file at some point too. I uninstalled the addon, manually wiped the Saved Variables files and reinstalled and no more errors. Apologies for bothering you with an issue with such a simple fix! 😅

**Comment by fstenstrom** [comment]
No problem. I know people before have patched that file before, but not heard about any issues before. While not officially supported, it would be good if the addon at least didn't crash. Created issue for fixing: #118
