### ISSUE TITLE
[ElvUI] Annoying blank box

### ISSUE THREAD

**Issue by cwwood0322** [fstenstrom/world-boss-timers#39]
I am having an issue where when changing a toon's spec or even after loading screens due to hearthing, teleporting, taking portals and so on that a blank box pops up on the center of my screen quite often. I see there has been some previous conflicts with Elvui before from previous comments on the addon and I don't know if that may be contributing to the issue. It is getting really annoying having to reload often to get rid of the dang box. I am posting a screenshot also.
![2019-11-20](https://user-images.githubusercontent.com/30670064/69474716-db59d680-0d89-11ea-8a07-504bd1188ccd.png)

**Comment by fstenstrom** [comment]
I can't replicate this (tried to change spec, teleport, HS)

Does it happen if you have only ElvUI + WBT activated?

**Comment by cwwood0322** [comment]
I believe so, I always use Elvui and it does not show up when WBT is enabled.

**Comment by fstenstrom** [comment]
I don't have the time to check it right now, but if more get this probably can debug it like this (note to self):

- add an "OnEnter" event on all frames I create, and then register callback that prints some frame ID (hopefully AceGUI doesn't create more frames than the obvious ones)
- distribute as alpha/dev-version

I can't check names of frames through /fstack, because it's Ace that sets it (or well, does not set it actually), and there seems to be no easy way to modify it
