### ISSUE TITLE
Separate Realm and WM options

### ISSUE THREAD

**Issue by dandepeched** [fstenstrom/world-boss-timers#70]
Right now wbt addon has single option for showing different realms and WM mode. It would be useful to have this options separated as for example in Pandaria all zones are crossrealm for the whole region, while WM mode is still a split for zones.

**Comment by fstenstrom** [comment]
So the use case would be that you set some option "ignore-cross-realm", then get Oondasta timer on realm A (Normal) and when you log in on realm B (Normal, not connected to A), you should still see the timer as "green" from realm A?

It could be a visual aid, but the timer should still not be allowed to be shared when on realm B, since it's possible that the realms actually are not cross-realm. I believe this could happen due to spike in logged in players (unlikely), or if one of the realms is RP (I believe they are always separated from non-RP?). And there can probably also be other reasons. The main problem is that it's impossible to tell via API and I'd rather avoid heuristic solutions.

**Comment by dandepeched** [comment]
This should an option for those player (like me) who sure that their realms are shared. I'm playing in RU realms and all of them are sharing same phasing for Pandaria.
So no API check is expected, just manual "untick" option.
This is definitely not something must-have. Workaround can be to implement manual reset of unneeded timer (#25)

**Comment by fstenstrom** [comment]
Alright, just wanted to ensure I didn't miss anything.

**Comment by fstenstrom** [comment]
Heuristic with Realm and Warmode is going away. Only shard ID will be used. Closing.
