### ISSUE TITLE
Rukhmar Boss Has no Notification Popup Alert

### ISSUE THREAD

**Issue by Bublek** [fstenstrom/world-boss-timers#86]
So for me Rukhmar Boss Notification stopped showing up, timer works still but no popup. Tried fresh addon install - didn't fix it.

**Comment by fstenstrom** [comment]
Can you clarify what the "popup" is? And does it work on other bosses?

The only alerts that should play are:

- Sound alert before spawn (10 sec default)
- Sound alert + game icon flashing (if you're tabbed out), on boss combat detected

There used to be a /say message, but was removed a long time ago (in 8.2.5 due to Blizzard API restrictions).
