### ISSUE TITLE
Timer keeps disappearing 

### ISSUE THREAD

**Issue by QueenofDarkness79** [fstenstrom/world-boss-timers#96]
My timer used to show the kills on all toons, now when I kill a rare with a timer and I leave that zone the timer clears. sometimes it comes back when another rare with timer is killed but now the timer isn't working at all. I even uninstalled it and reinstalled it. not sure what else to try.

**Comment by fstenstrom** [comment]
The issue is sharding. The addon now only shows timers that are guaranteed to be on your shard, unless you enable the option to show timers for other shards.

Without the option, when you log in or switch zone, the addon no longer knows what shard you are on, so it hides the timers until it can find which shard the player is on.

I understand that this is confusing, and I'll try to think of an improvement for it. Perhaps just by making the option enabled by default.

**Comment by bunster** [comment]
This change has been nothing but a downgrade to the function of the addon for me. I've never once been on the wrong shard for a kill.

**Comment by fstenstrom** [comment]
Update to previous comment: I think it's better to make these changes:

1. Assume that the previous shard is the correct one. This allows timers to not appear like they are missing until shard is identified.
2. Add option to color timers that are on the assumed shard (in grey or so)
3. Continue to not allow sharing of timers unless it's guaranteed that the current shard is known and matches the timer's
4. Add [Info] message if a "green" timer (i.e. a boss about to spawn on current assumed shard) is proven to be invalid, since the player is actually on another shard
