### ISSUE TITLE
pre-spawn alert not working

### ISSUE THREAD

**Issue by hollo6** [fstenstrom/world-boss-timers#97]
I want to set an alert (x sec before spawn) but it does nothing. I've even tried to change the timer value and the sound in case it was an initialization issue or something with some sounds but to no avail.
No sound is being played and no client icon flash either, so the spawn alert function never fires.

**Comment by fstenstrom** [comment]
Works for me. If anyone else is having the same issue then please comment, and I'll add debug logging.

**Comment by hollo6** [comment]
Since writing this ticket, I have discovered that it _sometimes_ works but it's rare and I can't find anything that could explain the difference. I'm using the same addons on half my characters and almost none on the other half, this problem is present on all and sometimes it works, sometimes not, for the same character.
Debug logging would be great.

**Comment by fstenstrom** [comment]
Poked at that code a bit in #100. Maybe helps. Will release a new version later today. If it still doesn't work after I'll look into it more.

**Comment by fstenstrom** [comment]
Great to hear that it seems to work now!

It's intentional that expired timers don't give alerts. I agree that it would make sense on bosses with fixed respawn time.

Maximum value is actually 5 min (you can write 300 in the box instead of using the slider), but it was never intended to be used like that, only to give you enough time to tab back before the boss gets one-shot. And yes, even if you change it to 5 min the alert won't play if you're in the wrong zone. But I understand that your scenario is also common.

I'll create issues for both cases, but most likely I won't fix/consider them (or any other non-bug issues) until the summer.

**Comment by hollo6** [comment]
Alright, thank you very much for the fix and the explanation! These can wait until the summer. :)
